#include<bits/stdc++.h>
#define up(x,a,b) for(ll x=a;x<=b;++x)
#define down(x,a,b) for(ll x=a;x>=b;--x)
#define mem(a,x) memset(a,x,sizeof(a))
using namespace std;
typedef long long ll;
int n,S,t,A,B;

int main(){
    ios::sync_with_stdio(0);
    cin>>n;
    while(n--){
        cin>>S>>t>>A>>B;
        up(i,1,S){
            int x1,x2,x3,y1,y2,y3,T;
            cin>>x1>>y1>>x2>>y2>>x3>>y3>>T;
            
        }
    }
    return 0;
}